//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DipositInfo
    {
        public int Id { get; set; }
        public Nullable<int> S_Id { get; set; }
        public string S_Name { get; set; }
        public Nullable<int> DipositAmount { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<System.DateTime> D_Date { get; set; }
        public string Discription { get; set; }
        public Nullable<int> ExpensesAmount { get; set; }
        public Nullable<System.DateTime> E_Date { get; set; }
    }
}
