//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenderInfo
    {
        public int G_Id { get; set; }
        public string G_Name { get; set; }
    }
}
