//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyTransectionTable
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> GiverId { get; set; }
        public Nullable<int> ReciverId { get; set; }
        public string Time { get; set; }
        public Nullable<int> PurposeId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> MoneyType { get; set; }
        public Nullable<int> Money { get; set; }
        public string C_User { get; set; }
    
        public virtual PurposeInfo PurposeInfo { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
        public virtual StudentInfo StudentInfo1 { get; set; }
    }
}
