//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOutDetail
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> InDate { get; set; }
        public Nullable<int> P_Id { get; set; }
        public Nullable<int> QTY { get; set; }
        public string GiverName { get; set; }
        public string ReceiverName { get; set; }
        public string OldOrNew { get; set; }
    
        public virtual ProductStockDetail ProductStockDetail { get; set; }
    }
}
