//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStockDetail()
        {
            this.ProductOutDetails = new HashSet<ProductOutDetail>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string P_SerialNumber { get; set; }
        public Nullable<int> P_Catagory { get; set; }
        public string P_Location { get; set; }
        public Nullable<int> P_QTY { get; set; }
        public Nullable<System.DateTime> P_In_Date { get; set; }
        public string P_Condition { get; set; }
        public string P_PersonName { get; set; }
        public string P_Remark { get; set; }
    
        public virtual ProductCatagory ProductCatagory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOutDetail> ProductOutDetails { get; set; }
    }
}
