//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInfo()
        {
            this.MoneyTransectionTables = new HashSet<MoneyTransectionTable>();
            this.MoneyTransectionTables1 = new HashSet<MoneyTransectionTable>();
            this.PersonalDipositInfoes = new HashSet<PersonalDipositInfo>();
        }
    
        public int Id { get; set; }
        public Nullable<long> S_Id { get; set; }
        public string S_Name { get; set; }
        public Nullable<int> S_GenderId { get; set; }
        public Nullable<int> S_DepId { get; set; }
        public string S_Address { get; set; }
        public Nullable<int> S_Phonse { get; set; }
        public Nullable<System.DateTime> S_DateOfBirth { get; set; }
        public string S_Discription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyTransectionTable> MoneyTransectionTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyTransectionTable> MoneyTransectionTables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalDipositInfo> PersonalDipositInfoes { get; set; }
    }
}
